### ISSUE TITLE
Issue by elm-ui install

### ISSUE THREAD

**Issue by pyladune** [gdotdesign/elm-ui#23]
I did follow the basic step from the readme but I got an error i do not know ho to handle
Thanks

seb@Jessie:~/Sites/elmui$ elm-ui install
Installing Elm packages...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/lib/node_modules/elm-ui/node_modules/elm/Elm-Platform/0.16.0/.cabal-sandbox/bin/elm-package ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:141:18)
    at node.js:933:3

**Comment by gdotdesign** [comment]
This is probably the related to this issue https://github.com/gdotdesign/elm-ui/issues/18
