### ISSUE TITLE
Error: Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 6.x

### ISSUE THREAD

**Issue by Arsca** [gdotdesign/elm-ui#30]
Hi,

Nice project! I'm eager to test it out, but unfortunately I cannot as after issuing the 

> elm-ui init appi

It throws this error

``````
/usr/local/lib/node_modules/elm-ui/node_modules/node-sass/lib/index.js:14
    throw new Error(errors.missingBinary());
    ^

Error: Missing binding /usr/local/lib/node_modules/elm-ui/node_modules/node-sass/vendor/darwin-x64-48/binding.node
**Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 6.x**

Found bindings for the following environments:
  - OS X 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (/usr/local/lib/node_modules/elm-ui/node_modules/node-sass/lib/index.js:14:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/elm-ui/bin/lib/render/css.js:3:12)
    at Module._compile (module.js:541:32)```
``````

**Comment by gdotdesign** [comment]
Elm-UI uses node-sass (https://github.com/sass/node-sass/issues?utf8=✓&q=is%3Aissue%20is%3Aopen) to compile CSS and this is an error of that package. 

I suspect it has to do something with your environment, maybe this issue can help https://github.com/sass/node-sass/issues/1527

**Comment by Arsca** [comment]
Thanks that helped! 
First I removed the elm-ui  and elm as well.
I reinstalled both and it works ok.

**Comment by Singh-KiaTec** [comment]
https://stackoverflow.com/a/49669424/9601544
