### ISSUE TITLE
Can't run elm-ui server, throws js effor

### ISSUE THREAD

**Issue by krothmuller** [gdotdesign/elm-ui#49]
When I run the server I get this error.. Not sure where to go from here? Any thoughts...

Packages configured successfully!
iMac:my-elm-ui Ken16$ elm-ui server
Listening on localhost:8001
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8001
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at Application.app.listen (/usr/local/lib/node_modules/elm-ui/node_modules/koa/lib/application.js:74:24)
    at Object.module.exports [as serve] (/usr/local/lib/node_modules/elm-ui/bin/lib/command/serve.js:66:7)
    at Command.<anonymous> (/usr/local/lib/node_modules/elm-ui/bin/index.js:53:11)
    at Command.listener (/usr/local/lib/node_modules/elm-ui/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
iMac:my-elm-ui Ken16$

**Comment by gdotdesign** [comment]
It seems something is using port 8001 on your machine.

**Comment by krothmuller** [comment]
Thanks... didn't think I was running anything on that port, but restarted iTerm and got the "running" info displayed, but... then got a JS error (it kinda looks like nothing is being compiled). 

You have errors in of your Elm file(s):
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/lib/node_modules/elm-ui/node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm-make ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

and got a (index):12 Uncaught ReferenceError: Elm is not defined. There is no reference to the CSS file, etc. Maybe I should try reinstalling the npm package???

**Comment by gdotdesign** [comment]
Reinstalling might help but it seems to be the same problem that's in this issue https://github.com/gdotdesign/elm-ui/issues/18

**Comment by gdotdesign** [comment]
I'm closing this since I just released 1.0.0 which moves the development environment functionality to https://github.com/gdotdesign/elm-dev-env.If the problem persist please open an issue there.
