### ISSUE TITLE
Under Windows, elm-ui install gives an error

### ISSUE THREAD

**Issue by richardhaven** [gdotdesign/elm-ui#56]
After installing elm-ui, init a new directory, elm-ui install in that directory gives:
bash$ elm-ui install
Resolving versions...
Starting downloads...

fs.js:809
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EPERM: operation not permitted, rename 'C:\Users\richard\Dropbox\Projects\test\elm-stuff\packages\coreytrampe\elm-vendor\elm-vendor-2.0.3' -> 'C:\Users\richard\Dropbox\Projects\test\elm-stuff\packages\coreytrampe\elm-vendor\2.0.3'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at C:\Users\richard\AppData\Roaming\npm\node_modules\elm-ui\node_modules\elm-github-install\src\index.js:43:16
    at ZipFile.<anonymous> (C:\Users\richard\AppData\Roaming\npm\node_modules\elm-ui\node_modules\extract-zip\index.js:29:11)
    at emitNone (events.js:86:13)
    at ZipFile.emit (events.js:185:7)
    at FdSlicer.<anonymous> (C:\Users\richard\AppData\Roaming\npm\node_modules\elm-ui\node_modules\yauzl\index.js:182:10)
    at FdSlicer.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at FdSlicer.emit (events.js:185:7)
bash$

**Comment by gdotdesign** [comment]
It seems that the script does not have permission to rename directories. Elm-UI uses an older version of `elm-github-install` which might cause this, can you install latest version of it and instead of `elm-ui install` use `elm-install` (it does the same thing).

**Comment by gdotdesign** [comment]
I'm closing this since I just released 1.0.0 which moves the development environment functionality to https://github.com/gdotdesign/elm-dev-env.If the problem persist please open an issue there.
